"""Baseline schema: extensions, all tables from metadata, performance indexes.

This baseline materialises the current ``Base.metadata`` (which intentionally
includes the Month-2 agent tables once they are defined) plus the pgvector + FTS
indexes. Subsequent schema changes should be added as autogenerated revisions
(`alembic revision --autogenerate -m "..."`).

Revision ID: 0001_baseline
Revises:
Create Date: 2026-06-06
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

from app.db import models  # noqa: F401 - register models on Base
from app.db.indexes import apply_indexes
from app.db.session import Base

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    bind.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))
    bind.execute(sa.text("CREATE EXTENSION IF NOT EXISTS pg_trgm"))
    Base.metadata.create_all(bind=bind)
    apply_indexes(bind)


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
